### ISSUE TITLE
Paper not found

### ISSUE THREAD

**Issue by Inferencer** [Jarvisss/Relightable_human_recon#1]
I cannot seem to find your paper when searching for 

> Relightable Detailed Human Reconstruction from Sparse Flashlight Images

Could you provide a link to your paper?

**Comment by Jarvisss** [comment]
Thank you for your interest in our work. Unfortunately, our paper is under review and may not be available at this time.
Once the article is accepted, I will take the time to attach the link to the paper and update the code.
